diff TestProjection/CGL_1_A-out1.txt TestProjection/out1.txt
diff  TestProjection/CGL_1_A-out2.txt TestProjection/out2.txt
diff  TestProjection/CGL_1_A-out3.txt TestProjection/out3.txt
diff  TestProjection/CGL_1_A-out4.txt TestProjection/out4.txt
diff  TestProjection/CGL_1_A-out5.txt TestProjection/out5.txt
diff  TestProjection/CGL_1_A-out6.txt TestProjection/out6.txt
diff  TestProjection/CGL_1_A-out7.txt TestProjection/out7.txt
diff  TestProjection/CGL_1_A-out8.txt TestProjection/out8.txt
diff  TestProjection/CGL_1_A-out9.txt TestProjection/out9.txt
diff  TestProjection/CGL_1_A-out10.txt TestProjection/out10.txt
diff  TestProjection/CGL_1_A-out11.txt TestProjection/out11.txt
diff  TestProjection/CGL_1_A-out12.txt TestProjection/out12.txt
diff  TestProjection/CGL_1_A-out13.txt TestProjection/out13.txt
diff  TestProjection/CGL_1_A-out14.txt TestProjection/out14.txt
diff  TestProjection/CGL_1_A-out15.txt TestProjection/out15.txt
